import { getAllProjects } from "@/lib/wordpress";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Projecten",
  description: "Generated by create next app",
};

export default async function Projects() {
  const projects = await getAllProjects();

  console.log(projects);

  return (
    <div className="">
      {projects.length > 0 &&
        projects.map((project) => {
          return (
            <Link href={`/projecten/${project.slug}`} key={project.id}>
              <p>{project.title.rendered}</p>
            </Link>
          );
        })}
    </div>
  );
}
