import { getAllProjects } from "@/lib/wordpress";
import { Metadata } from "next";
// import Link from "next/link";
import Card from "../components/card";

export const metadata: Metadata = {
  title: "Projecten",
  description: "Generated by create next app",
};

export default async function Projects() {
  const projects = await getAllProjects();

  console.log(projects);

  return (
    <div className="grid grid-cols-2 gap-4 py-4">
      <Card />

      {/* {projects.length > 0 &&
        projects.map((project) => {
          return (
            <Link
              className="bg-orange-200"
              href={`/projecten/${project.slug}`}
              key={project.id}
            >
              <p>{project.title.rendered}</p>
            </Link>
          );
        })} */}
    </div>
  );
}
