import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import BodyWithBackground from "./components/bodyWithBackground";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <BodyWithBackground className={`antialiased min-h-dvh container`}>
        <Header />
        {children}
      </BodyWithBackground>
    </html>
  );
}
